// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqdfvfhzxngzbzantbak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxZGZ2Zmh6eG5nemJ6YW50YmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTA4NzcsImV4cCI6MjA3NDkyNjg3N30.kk8Y0ErjigFsXJvIH6R-8PSy05610-93qaLeuhyBTmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});